### PR TITLE
openfl-next compilation fix

### PR DESCRIPTION
**Pull request by eliasku**
More information on https://github.com/fbricker/haxe-ga/issues/13

### CODE REVIEW

**Comment by eliasku** [comment]
ehhh...

**Comment by eliasku** [comment]
`openfl-next` is not working, we need to use `openfl_next` define, with underscore symbol. Anyway, I've closed the PR because it seems like the right solution is coming from here https://github.com/SharkPunch/haxe-ga/commit/e3dd61170ed8b5e59dced54eb34c4fe5f032acb0

**Comment by fbricker** [comment]
Hi, thanks for the tip. I'll try to provide a solution for both cases using this solution :)

**Comment by fbricker** [comment]
Hi, I've just taken this patch and added to haxe-ga. It's already on haxe-lib (haxe-ga version 0.5.0), so now haxe-ga it's compatible with both (openfl-legacy and openfl-next). Thanks!

**Comment by eliasku** [comment]
Great! Thank you!

**Pull request closed without merging**
